services:
    _defaults:
        autowire: true
        autoconfigure: true

    UnKonf\Sulu\SchemaOrgEventBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php, Wrapper}'

    UnKonf\Sulu\SchemaOrgEventBundle\Admin\:
        resource: '../../Admin'
        tags: ['sulu.admin', {name: 'sulu.context', context: 'admin'}]

    UnKonf\Sulu\SchemaOrgEventBundle\Controller\Admin\:
        resource: '../../Controller/Admin'
        tags: ['controller.service_arguments', {name: 'sulu.context', context: 'admin'}]
